# Do not touch this, if you are not asked to
# If you get an error about your config not being up-to-date, then
# go to the EnchantGUI bukkit page for instructions.
version: 1.2

# Enable news from the developer. The news are fetched from my website.
enable-news: true

# If set to true, the enchant icons will be shown as the item they can enchant.
# If set to false, the enchant icons will all be enchanted books.
show-enchants-as-items: true

# Enchant prices
# You can set a price for each individual level
# You can also use all: <price> to set a price for all enchant levels.
arrow-damage:
    all: 500
arrow-fire:
    all: 400
arrow-infinite:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
arrow-knockback:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
damage-all:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
damage-arthropods:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
damage-undead:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
dig-speed:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
durability:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
fire-aspect:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
knockback:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
loot-bonus-blocks:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
loot-bonus-mobs:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
luck:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
lure:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
oxygen:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
protection-environmental:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
protection-explosions:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
protection-fall:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
protection-fire:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
protection-projectile:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
silk-touch:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
thorns:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500
water-worker:
    level1: 100
    level2: 200
    level3: 300
    level4: 400
    level5: 500