name: EnchantGUI
version: 1.2
main: me.tychsen.enchantgui.Main

author: Dentych
dependency: Vault

commands:
    eshop:
        description: Command for the EnchantGUI plugin
        usage: Simply just /eshop