name: EnchantGUI
version: 1.3.2
main: me.tychsen.enchantgui.Main

author: Dentych
dependency: Vault

commands:
    genchant:
        description: Command for the EnchantGUI plugin
        usage: Simply just /genchant